# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65b50e029f822b3ed2158b3e576fd935dd05a967972a29153e28b49eba9c50f78b23a6cbdad8e8d724d57bb6f0c1bf78b3200ed11d9e0b6c724ababedae3d2e2

test:
  secret_key_base: a1587ca965f66f7c14ebcd949e697b9353646d0189edba3d085b113ccd67ec15fad43dfed422116b6a97191b6a1ee80ce21d4a9e805bd72dfd6836e83694bcd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
